/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IntelPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canDecrypt"
      | "ciphertext"
      | "contribute"
      | "contributionOf"
      | "currency"
      | "currencyDecimals"
      | "deadline"
      | "investigator"
      | "isUnlocked"
      | "minContributionForDecrypt"
      | "threshold"
      | "totalContributions"
      | "unlocked"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Contributed" | "Unlocked" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canDecrypt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ciphertext",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributionOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "currency", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currencyDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "investigator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUnlocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minContributionForDecrypt",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "threshold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalContributions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unlocked", values?: undefined): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "canDecrypt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ciphertext", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contributionOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "currency", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currencyDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "investigator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isUnlocked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minContributionForDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "threshold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlocked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ContributedEvent {
  export type InputTuple = [
    contributor: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [
    contributor: string,
    amount: bigint,
    newTotal: bigint
  ];
  export interface OutputObject {
    contributor: string;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnlockedEvent {
  export type InputTuple = [totalRaised: BigNumberish];
  export type OutputTuple = [totalRaised: bigint];
  export interface OutputObject {
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [investigator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [investigator: string, amount: bigint];
  export interface OutputObject {
    investigator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IntelPool extends BaseContract {
  connect(runner?: ContractRunner | null): IntelPool;
  waitForDeployment(): Promise<this>;

  interface: IntelPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canDecrypt: TypedContractMethod<
    [contributor: AddressLike],
    [boolean],
    "view"
  >;

  ciphertext: TypedContractMethod<[], [string], "view">;

  contribute: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  contributionOf: TypedContractMethod<
    [contributor: AddressLike],
    [bigint],
    "view"
  >;

  currency: TypedContractMethod<[], [string], "view">;

  currencyDecimals: TypedContractMethod<[], [bigint], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  investigator: TypedContractMethod<[], [string], "view">;

  isUnlocked: TypedContractMethod<[], [boolean], "view">;

  minContributionForDecrypt: TypedContractMethod<[], [bigint], "view">;

  threshold: TypedContractMethod<[], [bigint], "view">;

  totalContributions: TypedContractMethod<[], [bigint], "view">;

  unlocked: TypedContractMethod<[], [boolean], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canDecrypt"
  ): TypedContractMethod<[contributor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "ciphertext"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contribute"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contributionOf"
  ): TypedContractMethod<[contributor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "currency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currencyDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "investigator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isUnlocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "minContributionForDecrypt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "threshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalContributions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlocked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Contributed"
  ): TypedContractEvent<
    ContributedEvent.InputTuple,
    ContributedEvent.OutputTuple,
    ContributedEvent.OutputObject
  >;
  getEvent(
    key: "Unlocked"
  ): TypedContractEvent<
    UnlockedEvent.InputTuple,
    UnlockedEvent.OutputTuple,
    UnlockedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Contributed(address,uint256,uint256)": TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;
    Contributed: TypedContractEvent<
      ContributedEvent.InputTuple,
      ContributedEvent.OutputTuple,
      ContributedEvent.OutputObject
    >;

    "Unlocked(uint256)": TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;
    Unlocked: TypedContractEvent<
      UnlockedEvent.InputTuple,
      UnlockedEvent.OutputTuple,
      UnlockedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
